"""Definitions in やさしい日本語 (Easy/Simplified Japanese).

Like Nuance, this is LLM-generated by design: JMdict only provides English
glosses, and there's no equivalent free dictionary source for short,
plain-Japanese explanations of a word's meaning. Requires
ANTHROPIC_API_KEY; if it's not set (or --no-llm is passed), the field is
left blank and flagged rather than faked.
"""

import os

_MODEL = os.environ.get("DEFINITION_MODEL", "claude-sonnet-5")

_SYSTEM_PROMPT = (
    "あなたは日本語学習者向けのAnkiカードのために、単語の意味を「やさしい日本語」"
    "で説明します。やさしい日本語とは、難しい漢字や語彙を避け、短く分かりやすい"
    "文で書く日本語です。辞書的な説明を1〜2文で、やさしい日本語で書いてください。"
    "英語は使わないでください。例文をそのまま繰り返さないでください。"
)


def generate(word: str, sentence: str, english_gloss: str = "") -> tuple[str, bool]:
    """Return (definition_text, generated). generated=False means the
    field should be left blank and flagged (no API key, or the call
    failed). `english_gloss`, when available (JMdict, via
    dictionary.definition()), is passed in as grounding context so the
    model paraphrases a real definition instead of guessing from scratch."""
    try:
        import anthropic
    except ImportError:
        return "", False

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        return "", False

    client = anthropic.Anthropic(api_key=api_key)
    user_prompt = f"単語: {word}\n例文: {sentence}\n"
    if english_gloss:
        user_prompt += f"参考(英語の辞書的定義): {english_gloss}\n"
    user_prompt += "\nこの単語の意味を、やさしい日本語で説明してください。"
    try:
        response = client.messages.create(
            model=_MODEL,
            max_tokens=200,
            system=_SYSTEM_PROMPT,
            messages=[{"role": "user", "content": user_prompt}],
        )
    except Exception:
        return "", False

    text = "".join(block.text for block in response.content if hasattr(block, "text")).strip()
    if not text:
        return "", False
    return text, True
